name: Quality Assurance
on: [ pull_request, push, workflow_call ]
jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.12

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      #----------------------------------------------
      #               check-out repo
      #----------------------------------------------
      - uses: actions/checkout@v4

      - name: Install poetry
        uses: abatilo/actions-poetry@v3

      - uses: actions/cache@v3
      #----------------------------------------------
      #           install & configure poetry
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run tests
        run: |
          make test
        env:
          DJANGO_PROJECT_DATABASES: '{"default":{"HOST":"db"}}'
          DJANGO_PROJECT_LOCAL_SETTINGS_PATH: './src/config/settings/templates/settings.github.py'
